baseURL = "http://example.org/"
theme = "m10c"
title = "睡前不喝茶's blog"
languageCode = "zh-cn"

[params]
  author = "啊涛"
  description = "吃饭时吃饭，睡觉时睡觉"
  avatar = "aTao.jpg"
  menu_item_separator = " - "
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    primaryColor = "#57cc8a"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
